a = int(input("Please Enter the first num"))
b = int(input("Please Enter the second num"))
print ("Addition =",a+b)
print ("Subtraction =",a-b)
print ("Multiplication =",a*b)
print("Division =",a/b)